/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package master;

import javafx.application.Application;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.fxml.Initializable;
import javafx.geometry.Point2D;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.Pane;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;

public class App extends Application implements Initializable {

    private Parent root;
    SimulationClass simulation;

    private SceneSize windowSize;
    private SceneTools currentTool;
    final private String SELECTED_BTN_STYLE = "rgba(180,180,180,1);";
    private Point2D initialClickPoint;
    private boolean clickedOnShape;

    @FXML
    Pane simulationScene;

    @FXML
    Button startSimulationBtn;
    @FXML Button resizeScene;
    @FXML Button cleanSceneBtn;
    @FXML Button showPropertiesPanelBtn;
    @FXML Button stopSimulationBtn;

    @FXML Button rectangleToolBtn;
    @FXML Button elipseToolBtn;
    @FXML Button polygonToolBtn;
    @FXML Button lockedRectangleToolBtn;
    @FXML Button lockedElipseToolBtn;
    @FXML Button lockedPolygonToolBtn;
    @FXML Button moveToolBtn;
    @FXML Button deleteToolBtn;
    @FXML Button lockedPointToolBtn;

    @FXML Label mouseCoordonatesLbl;

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        root  = FXMLLoader.load(getClass().getResource("/source.fxml"));

        Scene scene = new Scene(root, 800, 600);
        scene.getStylesheets().add("style.css");

        primaryStage.minWidthProperty().setValue(600);
        primaryStage.minHeightProperty().setValue(400);
        primaryStage.resizableProperty().set(false);
        primaryStage.setTitle("TwoDeeCollision");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        setRectangleTool();

        startSimulationBtn.managedProperty().bind(startSimulationBtn.visibleProperty());
        resizeScene.managedProperty().bind(resizeScene.visibleProperty());
        cleanSceneBtn.managedProperty().bind(cleanSceneBtn.visibleProperty());
        showPropertiesPanelBtn.managedProperty().bind(showPropertiesPanelBtn.visibleProperty());

        stopSimulationBtn.managedProperty().bind(stopSimulationBtn.visibleProperty());
        stopSimulationBtn.setVisible(false);

        simulationScene.setOnMouseExited(e -> mouseCoordonatesLbl.setText("X: 0  Y: 0"));
        simulationScene.setOnMousePressed(this::scenePressHandler);
        simulationScene.setOnMouseReleased(this::sceneReleaseHandler);
        simulationScene.setOnMouseMoved(this::sceneMovementHandler);
        simulationScene.setOnMouseDragged(this::sceneDragHandler);
    }

    @FXML public void startSimulation(){
        startSimulationBtn.setVisible(false);
        resizeScene.setVisible(false);
        cleanSceneBtn.setVisible(false);
        showPropertiesPanelBtn.setVisible(false);
        stopSimulationBtn.setVisible(true);

        simulation = new SimulationClass(simulationScene);
        simulation.simulate();
    }

    @FXML public void stopSimulation(){
        try {simulation.stopSimulate();}
        catch (NullPointerException e)
        {
            System.err.println("NU S-A CREAT SIMULAREA---- - - - - - - - - - - - - ");
        }
        simulation = null;

        startSimulationBtn.setVisible(true);
        resizeScene.setVisible(true);
        cleanSceneBtn.setVisible(true);
        showPropertiesPanelBtn.setVisible(true);
        stopSimulationBtn.setVisible(false);
    }

    @FXML public void sceneResize(){
        setWindowSize();
        if(windowSize.getHeight()!= 0 && windowSize.getWidth()!=0)
        {
            Stage.getWindows().get(0).setHeight(Math.max(windowSize.getHeight(), 400));
            Stage.getWindows().get(0).setWidth(Math.max(windowSize.getWidth(), 600));
        }
    }

    @FXML public void cleanScene(){
        for(; 0 != simulationScene.getChildren().size(); )
            simulationScene.getChildren().remove(0);
    }

    @FXML public void setRectangleTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.RECTANGLE_TOOL;
        rectangleToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setElipseTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.ELIPSE_TOOL;
        elipseToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setPolygonTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.POLYGON_TOOL;
        polygonToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setLockedRectangleTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.LOCKED_RECTANGLE_TOOL;
        lockedRectangleToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setLockedElipseTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.LOCKED_ELIPSE_TOOL;
        lockedElipseToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setLockedPolygonTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.LOCKED_POLYGON_TOOL;
        lockedPolygonToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setMoveTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.MOVE_TOOL;
        moveToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setDeleteTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.DELETE_TOOL;
        deleteToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }
    @FXML public void setLockedPointTool(){
        setDefaultBtnBackground();
        currentTool = SceneTools.POINT_LOCK_TOOL;
        lockedPointToolBtn.setStyle("-fx-background-color:"+ SELECTED_BTN_STYLE);
    }

    private void setWindowSize(){
        windowSize = SceneSizeDialog.display("TwoDeeCollision Scene","What size should the scene be?");
    }

    private void setDefaultBtnBackground (){
        rectangleToolBtn.setStyle("");
        elipseToolBtn.setStyle("");;
        polygonToolBtn.setStyle("");
        lockedRectangleToolBtn.setStyle("");
        lockedElipseToolBtn.setStyle("");
        lockedPolygonToolBtn.setStyle("");
        moveToolBtn.setStyle("");
        deleteToolBtn.setStyle("");
        lockedPointToolBtn.setStyle("");
    }

    private void scenePressHandler(MouseEvent e){
        if (simulation != null)
        {
            clickedOnShape = true; //this will bypass any tool effect
            return;
        }

        initialClickPoint = new Point2D(e.getX(), e.getY());
        for(int i=0;i<simulationScene.getChildren().size(); i++)
            if(simulationScene.getChildren().get(i).contains(initialClickPoint))
                clickedOnShape = true;
    }

    private void sceneReleaseHandler(MouseEvent e){
        initialClickPoint = null;
        clickedOnShape = false;
    }

    private void sceneMovementHandler(MouseEvent e){
        mouseCoordonatesLbl.setText("X: " + e.getX() + "  Y: " + e.getY());
    }

    private void sceneDragHandler(MouseEvent e){
        mouseCoordonatesLbl.setText("X: " + e.getX() + "  Y: " + e.getY());
        switch (currentTool)
        {
            case RECTANGLE_TOOL:
                ToolBehaviour.rectangleToolDrag(initialClickPoint, e, simulationScene, clickedOnShape);
        }
    }

}